// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzAVuRnFpjMHYCGLoRdNT73u9RD6LB6gU',
    appId: '1:84159064145:web:0fc4ae6161f3a9541e3070',
    messagingSenderId: '84159064145',
    projectId: 'chat-project-37475',
    authDomain: 'chat-project-37475.firebaseapp.com',
    storageBucket: 'chat-project-37475.appspot.com',
    measurementId: 'G-GLHQ9L0BT8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBN7gKjn7AHebFgRo_9YqerrFladhJBdXo',
    appId: '1:84159064145:android:d6718c5d2bab9d721e3070',
    messagingSenderId: '84159064145',
    projectId: 'chat-project-37475',
    storageBucket: 'chat-project-37475.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYsOhhjQRLqiSot_qH3w65LGd6ZhhDry0',
    appId: '1:84159064145:ios:03d429234afb70c11e3070',
    messagingSenderId: '84159064145',
    projectId: 'chat-project-37475',
    storageBucket: 'chat-project-37475.appspot.com',
    androidClientId: '84159064145-nmf7jmqp12m8tdk8p9gkgmmkov8r4sn8.apps.googleusercontent.com',
    iosBundleId: 'com.example.myChatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBYsOhhjQRLqiSot_qH3w65LGd6ZhhDry0',
    appId: '1:84159064145:ios:3d72d65d1a5f85ee1e3070',
    messagingSenderId: '84159064145',
    projectId: 'chat-project-37475',
    storageBucket: 'chat-project-37475.appspot.com',
    androidClientId: '84159064145-nmf7jmqp12m8tdk8p9gkgmmkov8r4sn8.apps.googleusercontent.com',
    iosBundleId: 'com.example.myChatApp.RunnerTests',
  );
}
